/**
 * 壳文案字典 —— 题库/档位/报告正文之外的所有界面文字。
 *
 * 这是除 assessment-config.json 之外【唯一】允许出现中文字符的地方。
 * 其他 .ts / .tsx 文件里出现中日韩字符会被 `npm run lint:cjk` 拦下,构建失败。
 * 见 PROGRESS.md D5。
 *
 * Stage 1–11 只填 zh;en 留空即可(缺失时自动回落 zh 并在 dev 控制台告警)。
 * Stage 12 一次性补齐 en。
 */

export interface UiString {
  zh: string;
  en?: string;
}

export const UI_STRINGS = {
  // ── 通用 ────────────────────────────────────────────────
  'common.next': { zh: '下一题', en: 'Next' },
  'common.prev': { zh: '上一题', en: 'Back' },
  'common.submit': { zh: '提交', en: 'Submit' },
  'common.cancel': { zh: '取消', en: 'Cancel' },
  'common.confirm': { zh: '确认', en: 'Confirm' },
  'common.loading': { zh: '加载中', en: 'Loading' },
  'common.retry': { zh: '重试', en: 'Retry' },
  'common.close': { zh: '关闭', en: 'Close' },
  'common.download': { zh: '下载', en: 'Download' },
  'common.search': { zh: '搜索', en: 'Search' },
  'common.export': { zh: '导出 CSV', en: 'Export CSV' },
  'common.lang': { zh: 'EN', en: '中文' },
  'common.langSwitch': { zh: '切换语言', en: 'Switch language' },

  // ── 进度 ────────────────────────────────────────────────
  'progress.of': { zh: '第 {current} / {total} 题', en: 'Question {current} of {total}' },

  // ── 登录 / 重发链接 ────────────────────────────────────
  'login.title': { zh: '找回你的诊断链接', en: 'Resend your assessment link' },
  'login.placeholder': { zh: '手机号或邮箱', en: 'Phone number or email' },
  'login.action': { zh: '发送链接', en: 'Send link' },
  // 匹配成功与失败必须返回完全相同的文案,不能泄露名单信息
  'login.sent': {
    zh: '如果这个号码或邮箱在我们的名单里,链接已经发出,请查收 WhatsApp 与邮箱。',
    en: 'If this number or email is on our list, the link has been sent. Please check WhatsApp and your inbox.',
  },
  'login.throttled': {
    zh: '刚刚已经发送过一次,请稍等一分钟再试。',
    en: 'A link was just sent. Please wait a minute before trying again.',
  },
  'login.locked': {
    zh: '尝试次数过多,请一小时后再试。',
    en: 'Too many attempts. Please try again in an hour.',
  },
  'login.expired': {
    zh: '这个链接已失效,请重新获取。',
    en: 'This link is no longer valid. Please request a new one.',
  },

  // ── 魔法链接入口 / 失效页 ──────────────────────────────
  'landing.verifying': { zh: '正在验证链接…', en: 'Verifying your link…' },
  'expired.title': { zh: '链接已失效', en: 'Link no longer valid' },
  'expired.hint': {
    zh: '如果你还留着我们发的那条消息,请直接点里面的链接。找不到的话联系我们重发。',
    en: 'If you still have the message we sent, open the link inside it. Otherwise contact us for a new one.',
  },
  'placeholder.notImplemented': {
    zh: '这个页面还没做,会在标注的阶段实现。',
    en: 'This page is not built yet — it lands in the stage shown above.',
  },

  // ── Quiz ────────────────────────────────────────────────
  'quiz.profileSection': { zh: '先了解一下你的情况', en: 'A bit about you' },
  'quiz.questionSection': { zh: '增长罗盘测评', en: 'Growth Compass' },
  'quiz.saving': { zh: '正在保存…', en: 'Saving…' },
  'quiz.saveFailed': {
    zh: '这一题没保存成功,所以停在这里 —— 点重试,别往下走,否则这一题会缺。',
    en: "This answer didn't save, so we stopped here. Retry — skipping would leave a gap.",
  },
  'quiz.loadFailed': { zh: '载入答题进度失败。', en: 'Could not load your progress.' },
  'quiz.intro': { zh: '花大约 3 分钟,凭直觉选最接近的一项。答完立刻出你的增长罗盘分数。', en: 'About 3 minutes. Pick what fits best — your Compass score comes right after.' },
  'quiz.profileSectionTitle': { zh: '先了解一下你的生意', en: 'First, about your business' },
  'quiz.saved': { zh: '已保存', en: 'Saved' },
  'quiz.savingOne': { zh: '保存中', en: 'Saving' },
  'quiz.saveOneFailed': { zh: '这一题没存上,点一下重选即可重试', en: "This one didn't save — pick again to retry" },
  'quiz.submit': { zh: '提交,查看我的分数', en: 'Submit and see my score' },
  'quiz.unanswered': {
    zh: '还有 {n} 题没答,已帮你定位到第一题。',
    en: '{n} question(s) left — jumped you to the first.',
  },
  'quiz.stillSaving': {
    zh: '还有答案在保存,稍等一两秒再提交。',
    en: 'Some answers are still saving — try again in a second.',
  },
  'quiz.someFailed': {
    zh: '有 {n} 题没保存成功,已定位到第一题,重选一下就会重试。',
    en: '{n} answer(s) failed to save — jumped you to the first; re-pick to retry.',
  },
  'quiz.autosaveNote': {
    zh: '每答一题即自动保存。中途关掉,下次点链接回来会从这一题继续。',
    en: 'Saved after every answer. Close it and your link brings you back to this question.',
  },

  // ── Survey ──────────────────────────────────────────────
  'survey.title': { zh: '最后 7 个问题', en: 'Last 7 questions' },
  'survey.hint': {
    zh: '这几题不计分,但决定了报告里给你的建议有多贴合你的实际情况。',
    en: 'These are not scored, but they decide how well the report fits your actual situation.',
  },
  'survey.progress': { zh: '第 {current} / {total} 题', en: 'Question {current} of {total}' },
  'survey.optional': { zh: '选填', en: 'Optional' },
  'survey.multiHint': { zh: '可多选', en: 'Select all that apply' },
  'survey.submit': { zh: '提交并查看报告', en: 'Submit and see my report' },
  'survey.submitting': { zh: '正在生成你的报告…', en: 'Building your report…' },
  'survey.required': { zh: '这一题需要填写。', en: 'This one is required.' },
  'survey.tooLong': { zh: '最多 {max} 字。', en: 'Max {max} characters.' },
  'survey.saveFailed': {
    zh: '提交没成功,所以停在这里 —— 点重试,你填的内容还在。',
    en: "Submission didn't go through, so we stopped here. Retry — your answers are still here.",
  },
  'survey.incomplete': {
    zh: '测评题还没答完,先回去补齐才能出报告。',
    en: 'Some assessment questions are still unanswered — finish those first.',
  },
  'survey.charCount': { zh: '{n} / {max}', en: '{n} / {max}' },

  // ── Report ──────────────────────────────────────────────
  'report.loading': { zh: '正在生成你的报告…', en: 'Building your report…' },
  'report.notReady': { zh: '报告还没准备好 —— 先答完测评和问卷。', en: 'Your report is not ready yet — finish the assessment and survey first.' },
  'report.loadFailed': { zh: '载入报告失败。', en: 'Could not load your report.' },
  'report.you': { zh: '你', en: 'You' },
  'report.baseline.cohort': { zh: '本期基准', en: 'Cohort baseline' },
  'report.baseline.global': { zh: '历史基准', en: 'Historical baseline' },
  'report.total': { zh: '总分', en: 'Total score' },
  'report.section.radar': { zh: '你的增长罗盘', en: 'Your Growth Compass' },
  'report.section.tier': { zh: '你处在哪个阶段', en: 'Where you stand' },
  'report.section.cohort': { zh: '你在本期学员中的位置', en: 'Your position in this cohort' },
  'report.section.strengths': { zh: '你的强项', en: 'Your strengths' },
  'report.section.weaknesses': { zh: '最该先补的两环', en: 'The two links to fix first' },
  'report.section.submodules': { zh: '15 项子模块明细', en: '15 submodules in detail' },
  'report.section.actions': { zh: '接下来 30 天做这 3 件', en: 'Your next 30 days: 3 moves' },
  'report.section.nextStep': { zh: '你的下一步', en: 'Your next step' },
  'report.section.share': { zh: '带走这份报告', en: 'Take this report with you' },
  'report.cohort.band.top25': { zh: '你在本期前 25%', en: 'Top 25% of this cohort' },
  'report.cohort.band.q25_50': { zh: '你在本期前 25–50%', en: 'Upper-middle (25–50%)' },
  'report.cohort.band.q50_75': { zh: '你在本期 50–75%', en: 'Lower-middle (50–75%)' },
  'report.cohort.band.bottom25': { zh: '你在本期后 25%', en: 'Bottom 25% of this cohort' },
  'report.cohort.sameTier': { zh: '本期有 {n} 人和你在同一档', en: '{n} others in this cohort share your tier' },
  'report.cohort.diffHint': { zh: '各维度与本期均值的差值(正数在均值之上)', en: 'Each dimension vs the cohort mean (positive = above average)' },
  'report.weakness.current': { zh: '现状', en: 'Where you are' },
  'report.weakness.cost': { zh: '不补的代价', en: 'The cost of leaving it' },
  'report.weakness.rootCause': { zh: '根因', en: 'Root cause' },
  'report.cost.perMonth': { zh: '/ 月', en: '/ month' },
  'report.cost.approx': { zh: '约', en: 'approx.' },
  'report.cost.assumption': { zh: '这个估算基于', en: 'This estimate assumes' },
  'report.action.difficulty': { zh: '难度', en: 'Difficulty' },
  'report.action.impact': { zh: '预计影响', en: 'Expected impact' },
  'report.level.low': { zh: '低', en: 'Low' },
  'report.level.medium': { zh: '中', en: 'Medium' },
  'report.level.high': { zh: '高', en: 'High' },
  'report.mismatch': { zh: '你最想先动手的是「{want}」,而数据显示最该先补的是「{need}」—— 这个落差本身值得聊一次。', en: 'You want to fix "{want}" first, but the data points to "{need}". That gap is worth a conversation.' },
  'report.pdf.pending': { zh: 'PDF 正在生成,稍后回到这个链接即可下载。', en: 'Your PDF is being generated — come back to this link shortly to download.' },
  'report.pdf.print': { zh: '用浏览器打印 / 存 PDF', en: 'Print / save as PDF' },
  'report.pdf.rendering': { zh: 'PDF 正在生成…', en: 'Generating your PDF…' },
  'report.pdf.download': { zh: '下载 PDF 报告', en: 'Download the PDF report' },
  'report.pdf.opening': { zh: '正在打开…', en: 'Opening…' },
  'report.pdf.failed': {
    zh: 'PDF 自动生成没成功。用下面的浏览器打印同样能存成 PDF。',
    en: 'Automatic PDF generation did not succeed — the browser print option below works just as well.',
  },

  'report.section.evidence': { zh: '每一维为什么是这个分', en: 'Why each score is what it is' },
  'report.evidence.youChose': { zh: '你选的是', en: 'You chose' },
  'report.evidence.now': { zh: '现在', en: 'Now' },
  'report.evidence.target': { zh: '目标', en: 'Target' },
  'report.evidence.atTarget': { zh: '已经到顶格', en: 'Already at the top' },
  'report.evidence.unanswered': { zh: '未作答', en: 'Not answered' },
  'report.badge.priority': { zh: '优先', en: 'Priority' },
  'report.baseline.n': { zh: '{n} 份样本', en: '{n} samples' },
  'report.baseline.none': {
    zh: '本期样本只有你自己,暂无对比基准 —— 等同批次答满 10 份后这里会出现基准线。',
    en: 'You are the only sample so far, so there is no comparison line yet — it appears once 10 people in your cohort finish.',
  },
  'report.difficulty': { zh: '难度', en: 'Difficulty' },
  'report.impact': { zh: '影响', en: 'Impact' },

  // ── Admin ───────────────────────────────────────────────
  'admin.title': { zh: '学员名单', en: 'Roster' },
  'admin.login.title': { zh: '后台登录', en: 'Admin sign-in' },
  'admin.login.hint': {
    zh: '输入你的邮箱,我们会发一条登录链接。只有在允许名单里的邮箱能进后台。',
    en: 'Enter your email and we will send a sign-in link. Only allow-listed emails can enter.',
  },
  'admin.login.sent': { zh: '登录链接已发出,请查收邮箱。', en: 'Sign-in link sent — check your inbox.' },
  'admin.login.action': { zh: '发送登录链接', en: 'Send sign-in link' },
  'admin.forbidden': {
    zh: '这个账号不在后台允许名单里。换个账号,或者联系管理员把你加进名单。',
    en: 'This account is not on the admin allowlist. Use another account or ask to be added.',
  },
  'admin.signOut': { zh: '退出', en: 'Sign out' },
  'admin.refresh': { zh: '刷新', en: 'Refresh' },
  'admin.empty': { zh: '还没有任何准入记录。', en: 'No entitlements yet.' },
  'admin.phoneBad': { zh: '号码格式异常', en: 'Unparseable phone' },
  'admin.phoneRatio': {
    zh: '号码解析失败:{bad} / {total}({pct})',
    en: 'Unparseable phones: {bad} / {total} ({pct})',
  },
  'admin.phoneRatioOver': {
    zh: '超过 2% 阈值 —— GHL 里的号码质量比预期差,该回头看要不要加预处理了。',
    en: 'Above the 2% threshold — phone quality in GHL is worse than expected.',
  },
  'admin.filter.cohort': { zh: '全部批次', en: 'All cohorts' },
  'admin.filter.status': { zh: '全部状态', en: 'All statuses' },
  'admin.filter.minScore': { zh: '最低分', en: 'Min score' },
  'admin.filter.maxScore': { zh: '最高分', en: 'Max score' },
  'admin.filter.badPhoneOnly': { zh: '只看号码异常', en: 'Unparseable phones only' },
  'admin.col.name': { zh: '姓名', en: 'Name' },
  'admin.col.phone': { zh: '手机', en: 'Phone' },
  'admin.col.email': { zh: '邮箱', en: 'Email' },
  'admin.col.cohort': { zh: '批次', en: 'Cohort' },
  'admin.col.status': { zh: '状态', en: 'Status' },
  'admin.col.firstLogin': { zh: '登录时间', en: 'First login' },
  'admin.col.completed': { zh: '完成时间', en: 'Completed' },
  'admin.col.total': { zh: '总分', en: 'Score' },
  'admin.col.tier': { zh: '档位', en: 'Tier' },
  'admin.col.weakest': { zh: '最弱维度', en: 'Weakest' },
  'admin.col.actions': { zh: '操作', en: 'Actions' },
  'admin.col.pdf': { zh: 'PDF', en: 'PDF' },
  'admin.action.renderPdf': { zh: '重新生成 PDF', en: 'Re-generate PDF' },
  'admin.pdf.rendering': { zh: '生成中', en: 'Rendering' },
  'card.scoreLabel': { zh: '我的增长罗盘总分', en: 'My Growth Compass score' },
  'card.tierLabel': { zh: '当前档位', en: 'Current tier' },
  'card.cta': { zh: '扫码测你自己的', en: 'Take the diagnostic yourself' },
  'report.card.title': { zh: '分享卡', en: 'Share card' },
  'report.card.hint': { zh: '长按或右键保存,发朋友圈 / WhatsApp。卡片只有总分、档位与雷达形状,不含各维度分数。', en: 'Save it and post to your feed. The card shows only your total, tier and radar shape — no per-dimension scores.' },
  'report.card.square': { zh: '方形(朋友圈)', en: 'Square (feed)' },
  'report.card.tall': { zh: '竖版(IG / 小红书)', en: 'Vertical (IG / RED)' },
  'admin.tab.roster': { zh: '学员名单', en: 'Roster' },
  'admin.tab.dashboard': { zh: '批次看板', en: 'Cohort dashboard' },
  'admin.tab.funnel': { zh: '漏斗监控', en: 'Funnel' },
  'funnel.base': { zh: '本范围 {n} 人已付款', en: '{n} paid in this scope' },
  'funnel.stage.link_sent': { zh: '已发链接', en: 'Link sent' },
  'funnel.stage.logged_in': { zh: '已登录', en: 'Logged in' },
  'funnel.stage.started_answering': { zh: '已开始答题', en: 'Started answering' },
  'funnel.stage.survey': { zh: '已进问卷', en: 'Reached survey' },
  'funnel.stage.completed': { zh: '已完成', en: 'Completed' },
  'funnel.dropped': { zh: '掉 {n} 人', en: '{n} dropped' },
  'funnel.inconsistent': { zh: '⚠️ {n} 条记录的状态互相矛盾(例如已完成却没有发链接记录)—— 已按「走到后面就算走过前面」补齐,但那说明别处有问题,不是这块统计有问题', en: '⚠️ {n} record(s) have contradictory state — smoothed, but it points at a bug elsewhere' },
  'funnel.empty': { zh: '这个范围里还没有人', en: 'Nobody in this scope yet' },
  'admin.tab.insights': { zh: '问卷洞察', en: 'Survey insights' },
  'ins.search': { zh: '搜原文(例如:现金流)', en: 'Search answers (e.g. cash flow)' },
  'ins.section.highIntent': { zh: '高意向名单', en: 'High-intent list' },
  'ins.section.mismatch': { zh: '想修的 ≠ 该修的', en: 'Wants to fix ≠ needs to fix' },
  'ins.section.answers': { zh: '开放题原文', en: 'Open-text answers' },
  'ins.mismatchWhy': {
    zh: '这批人值得优先聊 —— 他们已经有改进意愿,只是方向选错了。沟通成本比「没意愿」的人低得多;而错的方向会让他们把力气花在收益最小的那一环上。「挨着」那一栏(选中最弱第二维)方向基本是对的,只是排序错,优先级低于「偏了」。',
    en: 'Talk to these first: they already want to improve, they are just aiming at the wrong link.',
  },
  'ins.count': { zh: '共 {n} 人填过问卷', en: '{n} completed the survey' },
  'ins.highIntentCount': { zh: '高意向 {n} 人', en: '{n} high intent' },
  'ins.align.aligned': { zh: '正中', en: 'On target' },
  'ins.align.second_weakest': { zh: '挨着', en: 'Second weakest' },
  'ins.align.mismatched': { zh: '偏了', en: 'Off target' },
  'ins.wants': { zh: '想修', en: 'Wants' },
  'ins.needs': { zh: '该修', en: 'Needs' },
  'ins.goal': { zh: '90 天目标', en: '90-day goal' },
  'ins.blocker': { zh: '最大阻碍', en: 'Biggest blocker' },
  'ins.noMatch': { zh: '没有匹配的原文', en: 'No matching answers' },
  'ins.empty': { zh: '这个范围里还没有人填过问卷', en: 'Nobody has completed the survey in this scope' },
  'ins.exportHighIntent': { zh: '导出高意向 CSV', en: 'Export high-intent CSV' },
  'admin.tab.live': { zh: '现场模式', en: 'Live mode' },
  'live.enterFullscreen': { zh: '全屏投影', en: 'Full screen' },
  'live.exitFullscreen': { zh: '退出全屏', en: 'Exit full screen' },
  'live.prev': { zh: '上一屏', en: 'Previous' },
  'live.next': { zh: '下一屏', en: 'Next' },
  'live.hint': { zh: '左右方向键切换。不会自动切屏。', en: 'Arrow keys to move. Never auto-advances.' },
  'live.testBanner': { zh: '⚠️ 演示数据 · 以下全部是造的,不是真实学员', en: '⚠️ DEMO DATA — none of this is real' },
  'live.allCohorts': { zh: '全部批次(不含测试)', en: 'All cohorts (excl. test)' },
  'live.slide.headline': { zh: '本批概况', en: 'At a glance' },
  'live.slide.radar': { zh: '五维平均', en: 'Dimension averages' },
  'live.slide.tier': { zh: '档位分布', en: 'Tier distribution' },
  'live.slide.weakest': { zh: '最弱维度分布', en: 'Weakest dimensions' },
  'live.people': { zh: '人', en: '' },
  'live.avgTotal': { zh: '平均总分', en: 'Average' },
  'live.completed': { zh: '已完成', en: 'Completed' },
  /**
   * 第一屏那行小字。**没有「本批」** —— 这一屏也可能是「全部批次」范围,
   * 那时「本批」是错的;而范围已经写在标题上了。
   */
  'live.completedCount': { zh: '{n} 人已完成', en: '{n} completed' },
  'live.empty': { zh: '这个范围里还没有人完成测评', en: 'Nobody has completed the assessment in this scope' },
  'dash.scope': { zh: '批次范围', en: 'Cohort scope' },
  'dash.scope.all': { zh: '全部批次(不含测试)', en: 'All cohorts (excluding test)' },
  'dash.testWarning': { zh: '你正在看测试 / 演示批次 —— 下面所有数字都是造的', en: 'You are viewing a TEST cohort — every number below is fabricated' },
  'dash.n': { zh: '本批 {n} 人已完成', en: '{n} completed in this cohort' },
  'dash.avgTotal': { zh: '平均总分', en: 'Average total' },
  'dash.section.radar': { zh: '五维平均', en: 'Dimension averages' },
  'dash.section.tier': { zh: '档位分布', en: 'Tier distribution' },
  'dash.section.weakest': { zh: '最弱维度分布', en: 'Weakest-dimension distribution' },
  'dash.section.questions': { zh: '每道题的选项分布', en: 'Per-question option spread' },
  'dash.questionsHint': { zh: '按集中度排序 —— 越靠前的题,全场答得越一致', en: 'Sorted by concentration — the most lopsided questions come first' },
  'dash.people': { zh: '{n} 人', en: '{n}' },
  'dash.showAllQuestions': { zh: '展开其余 {n} 题', en: 'Show {n} more questions' },
  'dash.collapseQuestions': { zh: '只看前 5 题', en: 'Show top 5 only' },
  'admin.action.reportHint': { zh: '用一条 180 秒有效的临时链接打开学员报告(会记入日志)', en: "Opens the learner's report with a 180-second link (logged)" },
  'admin.report.opening': { zh: '打开中', en: 'Opening' },
  'dash.lowSample': { zh: '样本 {n} 人,不足 {min} 人 —— 只给人数,不给比例', en: 'n={n}, below {min} — counts only, no percentages' },
  'dash.empty': { zh: '这个范围里还没有人完成测评', en: 'Nobody has completed the assessment in this scope yet' },
  'admin.showTest': { zh: '显示测试数据', en: 'Show test data' },
  'admin.testBadge': { zh: '测试', en: 'TEST' },
  'admin.testHidden': { zh: '另有 {n} 条测试数据已隐藏(CSV 导出一律不含)', en: '{n} test row(s) hidden (never included in the CSV export)' },
  'admin.card.errorLabel': { zh: '分享卡生成失败(不影响 PDF)', en: 'Share card failed (PDF unaffected)' },
  'admin.col.card': { zh: '分享卡', en: 'Card' },
  'admin.pdf.showError': { zh: '看错误', en: 'Why' },
  'admin.pdf.hideError': { zh: '收起', en: 'Hide' },
  'admin.pdf.errorLabel': { zh: 'PDF 生成失败', en: 'PDF render failed' },
  'admin.action.resend': { zh: '重发链接', en: 'Resend link' },
  'admin.action.rotate': { zh: '换新链接', en: 'New link' },
  'admin.action.revoke': { zh: '停用', en: 'Revoke' },
  'admin.action.report': { zh: '查看报告', en: 'View report' },
  'admin.revoked': { zh: '已停用', en: 'Revoked' },
  'admin.confirmRotate': {
    zh: '换新链接会让旧链接立刻失效,并给这个人重发一条新的。继续?',
    en: 'This kills the old link immediately and sends a new one. Continue?',
  },
  'admin.confirmRevoke': {
    zh: '停用会让这个人的链接立刻失效,而且【不会】发新的。继续?',
    en: 'This kills their link immediately and does NOT send a new one. Continue?',
  },
  'admin.notQueued': {
    zh: '已发出,但 GHL 没有把它放进执行队列 —— 先确认那条 workflow 是否已 Publish。',
    en: 'Sent, but GHL did not queue it — check whether the workflow is published.',
  },

  // ── PDF ─────────────────────────────────────────────────
  'pdf.generating': { zh: 'PDF 生成中', en: 'Generating PDF' },
  'pdf.ready': { zh: '下载 PDF 报告', en: 'Download PDF report' },
  'pdf.failed': { zh: '自动生成失败,可用浏览器打印保存', en: 'Auto-generation failed — use browser print instead' },
  'pdf.print': { zh: '用浏览器打印', en: 'Print with browser' },

  // ── 组件展示页(Stage 1 用,后续可删)──────────────────
  'showcase.title': { zh: 'Brutalist 组件层', en: 'Brutalist components' },
  'showcase.subtitle': {
    zh: 'Stage 1 地基。后面所有页面只用这里的组件,不再逐页新增。',
    en: 'Stage 1 foundation. All later pages compose from these — no per-page additions.',
  },
  'showcase.fontCheck': { zh: '字体渲染自检', en: 'Font rendering check' },
  'showcase.fontCommon': { zh: '常用字:盈利增长罗盘诊断报告', en: 'Common glyphs' },
  'showcase.fontRare': { zh: '生僻字:䶮 龘 靐 齉 麤', en: 'Rare glyphs' },
  'showcase.marks': { zh: '子模块标记(纯 CSS,不用字符)', en: 'Submodule marks (pure CSS, no glyphs)' },
  'showcase.markFull': { zh: '已具备', en: 'In place' },
  'showcase.markHalf': { zh: '部分具备', en: 'Partial' },
  'showcase.markEmpty': { zh: '缺失', en: 'Missing' },
  'showcase.dimColors': { zh: '六维分类色(仅作带墨边框的填充)', en: 'Dimension colours (bordered fills only)' },
  'showcase.fontNote': {
    zh: '生僻字若显示为方块,说明兜底字体未生效。PDF 渲染会出同样的问题。',
    en: 'Tofu boxes here mean the fallback font is not active. PDF rendering will fail the same way.',
  },
} as const satisfies Record<string, UiString>;

export type UiKey = keyof typeof UI_STRINGS;
